### ISSUE TITLE
Unhandled exception: Class 'int' has no instance getter 'name'.

### ISSUE THREAD

**Issue by filiph** [dart-lang/csslib#92]
csslib throws an unhandled error when parsing the following CSS.

Here's the stacktrace:

```
Unhandled exception:
NoSuchMethodError: Class 'int' has no instance getter 'name'.
Receiver: 0
Tried calling: name
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      _Parser.processSelectorExpression (package:csslib/parser.dart:1690:47)
#2      _Parser.processPseudoSelector (package:csslib/parser.dart:1605:20)
#3      _Parser.simpleSelectorTail (package:csslib/parser.dart:1545:16)
#4      _Parser.simpleSelector (package:csslib/parser.dart:1490:14)
#5      _Parser.simpleSelectorSequence (package:csslib/parser.dart:1403:11)
#6      _Parser.processSelector (package:csslib/parser.dart:1338:26)
#7      _Parser.processSelectorGroup (package:csslib/parser.dart:1320:27)
#8      _Parser._nestedSelector (package:csslib/parser.dart:1152:30)
#9      _Parser.processDeclarations (package:csslib/parser.dart:1181:27)
#10     _Parser.processRule (package:csslib/parser.dart:1105:37)
#11     _Parser.parse (package:csslib/parser.dart:206:20)
#12     parse (package:csslib/parser.dart:99:32)
#13     parseCss (package:linkcheck/src/parsers/css.dart:29:17)
```

Here's the exact CSS. Sorry for the huge blob, I'm currently not in position to try to minimize the repro.

[csslib-throws.css.zip](https://github.com/dart-lang/csslib/files/3224786/csslib-throws.css.zip)

**Comment by leonsenft** [comment]
@filiph What version are you on? Do you know if this is a regression introduced in version 0.16.0 https://pub.dev/packages/csslib#-changelog-tab-?

I wonder if the code I removed was masking this error somehow.

**Comment by filiph** [comment]
I'm on the latest version (0.16). I [upgraded from 0.14.6](https://github.com/filiph/linkcheck/commit/685be3a3f385381f6661d54d52d9ce81316f0530#diff-7ed8db171f9d2dbefb97f0043b4eb2ffL80) to see if that helps but it didn't.

**Comment by leonsenft** [comment]
Ah so the issue was present before upgrading? That's good to know, thank you.

**Comment by leonsenft** [comment]
Okay I found the culprit, here's a simple reproduction:

```css
.foo {
  border-radius: calc(0 - 1px);
}
```

Looking at the stack trace, you can see the parser fails trying to interpret this declaration as a selector. 
This is because when parsing a ruleset, each component is first interpreted as a selector.

If that succeeds, *and* the following character is a `{`, it then proceeds to parse this as a nested ruleset (certain directives support nesting such as `@keyframes`).

Otherwise, it will interpret this component as a declaration (which is the correct interpretation in this case).

This case is causing the first step to fail, because the `0 -` is tripping up the parser which thinks it's currently parsing a "selector expression" which according to the comments

> In CSS3, the expressions are identifiers, strings, or of the form "an+b".

Note `0 -` is expected to be the form `0n -` in this case.

The solution is that the parser should be seeing this is not a valid selector and falling back to the declaration path.

This issue ultimately stems from the fact the parser tries to fully parse the source in one pass, whereas the spec handles it incrementally, first breaking things into blocks: https://www.w3.org/TR/css-syntax-3/#parser-diagrams. I think such an approach would be beneficial, but is outside the scope of this issue.

**Comment by sjbanov** [comment]
I found this issue when I tried to use css variables with number in his name. 
For example, `var-level-1-normal`, corresponding to our design system terms. 

I propose to check possible functional pseudos.
